variable "audit_role_arn" {
 description = "The ARN of the IAM role attach the policy to"
 type = string
 default = "arn:aws:iam::429060775154:role/s1-cns-audit-2056384125320855810"
}
variable "audit_role_name" {
 description = "The name of IAM role attach the policy to"
 type = string
 default = "s1-cns-audit-2056384125320855810"
}
variable "root_ou_id" {
 description = "The name of IAM role attach the policy to"
 type = string
 default = "r-38w6"
}
variable "iam_path" {
 description = "The path for the IAM role to be created in AWS account."
 type = string
 default = "/"
}
variable "permission_boundary_arn" {
 description = "The ARN of the policy that is used to set the permissions boundary for the IAM role."
 type = string
 default = ""
}
variable "identifier" {
 description = "The unique identifier for the integration. This identifier is used to create unique resource names."
 type = string
 default = "2056384125320855810"
}
variable "enable_cloudtrail" {
 description = "Enable CloudTrail"
 type = string
 default = "Yes"
}
variable "marketplace_external_id" {
 description = "The external ID auto-generated by SentinelOne. Do not change this value."
 type = string
 default = "9f43b52f61d94bc6e6536592ae84f8ca5f6ea7f025e8f944a899f7c4cdbf3fa0"
}
variable "cloudtrail_bucket_name" {
 description = "The name of the S3 bucket to store CloudTrail logs."
 type = string
 default = "aws-controltower-logs-688567271939-us-east-1"
}
variable "cloudtrail_kms_arn" {
 description = "The ARN of the KMS key attached to the CloudTrail."
 type = string
 default = ""
}
variable "bucket_owner_account_id" {
 description = "The AWS account ID of the bucket owner."
 type = string
 default = "688567271939"
}
variable "is_organization_onboarding" {
 description = "Is the organization onboarding."
 type = string
 default = "No"
}
variable "existing_sns_topic_arn" {
 description = "The ARN of the existing SNS topic."
 type = string
 default = "arn:aws:sns:us-east-1:207567775001:aws-controltower-AllConfigNotifications"
}
variable "existing_sns_topic_account_id" {
 description = "The AWS account ID of the existing SNS topic."
 type = string
 default = "207567775001"
}
variable "audit_role_for_bucket_access" {
 description = "The ARN of the IAM role attach the policy to"
 type = string
 default = "arn:aws:iam::688567271939:role/s1-cns-audit-2056384125320855810"
}